repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
        args: ["--profile", "black"]
  - repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
        exclude: tests.*
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: |
          (?x)^(
            tests.*|
            mkdocs.yml
          )$
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: "^tests/resources/"
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: ["pydantic", "toml", "types-pyyaml", "types-requests", "types-pytz", "types-python-dateutil"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--recursive, "-q", "-c", "pyproject.toml"]
        additional_dependencies: ["toml"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: ["Flake8-pyproject"]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.0.5
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ["toml"]
      - id: sqlfluff-fix
        additional_dependencies: ["toml"]
exclude: 'dags/dbt/novicap/dbt_packages/.*'
