[tool.bandit]
exclude_dirs = ["tests"]
tests = ["B201", "B301"]
skips = ["B101", "B601"]

[tool.isort]
profile = "black"

[tool.black]
line-length = 119

[tool.flake8]
ignore = [
    'D203',
    'W503',
    'E203',
    'E266',
    'E501',
    'W503',
    'C901']
exclude = [
    '.tox',
    '.git',
    '__pycache__',
    'docs/source/conf.py',
    'sandbox/',
    'build',
    'dist',
    'tests/fixtures/*',
    '*.pyc',
    '*.egg-info',
    '.cache',
    '.eggs'
]
max-complexity=20
import-order-style='google'
max-line-length=119

[tool.coverage.xml]
output = "test-reports/coverage.xml"

[tool.coverage.html]
directory = "test-reports/htmlcov"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests/",
]

[tool.sqlfluff.core]
dialect = "snowflake"
templater = "jinja"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
large_file_skip_byte_limit = 0
rules = "L010, L019, L020, L021, L022, L025, L044, L051, L068, L030, L040, L063, L060, L038, L049, L053, L046, L001, L002, L018, L036, L041, L065, L009, L050, L026, L028, L057, L059, L035, L043, L045, L058, L042"

[tool.sqlfluff.indentation]
indented_joins = false
indented_using_on = true
template_blocks_indent = false

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "lower"

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = true

[tool.sqlfluff.templater.dbt]
project_dir = "./dags/dbt/novicap"

[tool.sqlfluff.layout.type.comma]
line_position = "leading"
